<?php 
$title = $this->translate('Add new blog');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('blog', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);

/* 
 * echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('Post_Text'));
echo $this->formSubmit($form->get('submit'));
OR echo $this->formCollection($form) they are the same;
*/
echo $this->formCollection($form);

echo $this->form()->closeTag();
?>