<?php 
$title = $this->translate('Delete Blog');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><?php  echo sprintf($this->translate('DELETE_CONFIRM'), $this->escapeHtml($this->escapeHtml($blog->getTitle()))) ?></p>
<?php
$url = $this->url('blog', array(
'action' => 'delete',
'id' => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo (int) $blog->getId(); ?>" />
<input type="submit" name="del" value="<?php echo $this->translate('Yes')?>" />
<input type="submit" name="nodel" value="<?php echo $this->translate('No')?>" />
</div>
</form>