<?php
// module/Blog/view/blog/blog/index.phtml:
$title = $this->translate('My Blog');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
<a href="<?php echo $this->url('blog', array('action'=>'add'));?>"><?php echo $this->translate('Add new blog')?></a>
</p>
<table class="table">
<tr>
<th><?php echo $this->translate('Title')?></th>
<th><?php echo $this->translate('Contents')?></th>
<th>&nbsp;</th>
</tr>
<?php foreach ($blogs as $blog) : ?>
<tr>

<td>
<a href="<?php echo $this->url('blog',
array('action'=>'view', 'id' => $blog->getId()));?>">
<?php echo $this->escapeHtml($blog->getTitle());?>
</a>
</td>

<td>
<a href="<?php echo $this->url('blog',
array('action'=>'view', 'id' => $blog->getId()));?>">
<?php echo $this->escapeHtml($blog->getContents());?>
</a>
</td>

<td>
<a href="<?php echo $this->url('blog',
array('action'=>'edit', 'id' => $blog->getId()));?>"><?php echo $this->translate('Edit')?></a>
<a href="<?php echo $this->url('blog',
array('action'=>'delete', 'id' => $blog->getId()));?>"><?php echo $this->translate('Delete')?></a>
</td>
</tr>
<?php endforeach; ?>
</table>